# Generated by Django 2.1 on 2019-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpapi',
            name='httpapi_assertcontent',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='断言内容'),
        ),
        migrations.AddField(
            model_name='httpapi',
            name='httpapi_asserttype',
            field=models.CharField(blank=True, choices=[('noselect', '无'), ('in', '包含'), ('status_code', '状态码')], max_length=50, null=True, verbose_name='断言类型'),
        ),
    ]
