# Generated by Django 2.1 on 2019-04-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190406_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httpapi',
            name='httpapi_assertcontent',
        ),
        migrations.RemoveField(
            model_name='httpapi',
            name='httpapi_asserttype',
        ),
    ]
