# Generated by Django 2.1 on 2019-04-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190406_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpapi',
            name='assertContent',
            field=models.CharField(default='', max_length=200, verbose_name='断言内容'),
        ),
        migrations.AddField(
            model_name='httpapi',
            name='assertType',
            field=models.CharField(choices=[('noselect', '无'), ('in', '包含'), ('status_code', '状态码')], default='', max_length=200, verbose_name='断言类型'),
        ),
    ]
